#!/bin/bash
############################  SETUP PARAMETERS
debug_mode=0

############################  BUNDLES LIST
history_substring_search="bundle/zsh-history-substring-search --squash https://github.com/zsh-users/zsh-history-substring-search.git master"
zsh_syntax_highlighting="bundle/zsh-syntax-highlighting --squash https://github.com/zsh-users/zsh-syntax-highlighting.git master"
zsh_base16="bundle/zsh-base16 --squash git@github.com:X4/zsh-base16.git master"


############################  BASIC SETUP TOOLS
msg() {
    printf '%b' "$1" >&2
}

error() {
    msg "\e[31m[✘]\033[0m ${1}${2}"
    exit 1
}

success() {
    if [ "$ret" -eq '0' ]; then
      msg "\e[32m[✔]\033[0m ${1}${2}"
    else
      error "${1}${2}"
    fi
}

debug() {
    if [ "$debug_mode" -eq '1' ] && [ "$ret" -gt '1' ]; then
      msg "An error occured in function \"${FUNCNAME[$i+1]}\" on line ${BASH_LINENO[$i+1]}, we're sorry for that."
    fi
}

program_exists() {
    local ret='0'
    type $1 >/dev/null 2>&1 || { local ret='1'; }

    # throw error on non-zero return value
    if [ ! "$ret" -eq '0' ]; then
    error "$2"
    fi
}

############################  SETUP ROUTINE

git_subtrees() {
    cd ~/.X4
    git subtree add  --prefix $1
    git subtree pull --prefix $1
    ret="$?"
    success "$2"
}

setup_shell() {
    msg "\n\nWhich shell do you want to setup?\n[\e[31m1\033[0m] Bash\n[\e[31m2\033[0m] ZSH\n[\e[31m3\033[0m] Fish\nChoose: "
    read -p "" $X4 ; echo ""
    if [[ $REPLY =~ ^[1]$ ]]; then
        ln -sfv $HOME/.X4/.bash* $HOME/
    fi
    if [[ $REPLY =~ ^[2]$ ]]; then
        ln -sfv $HOME/.X4/.zsh* $HOME/
    fi
    if [[ $REPLY =~ ^[3]$ ]]; then
        ln -sfv $HOME/.X4/.fish* $HOME/
    fi
    if [[ ! $REPLY -eq "" ]]; then
        ln -sfv $HOME/.X4/{.bcrc, .cvsignore, .gemrc, .inputrc, .irbrc, .tmux*} $HOME/
    fi
    ret="$?"
    success "$1"
}

############################  MAIN()
git_subtrees $history_substring_search	"installing bundle/zsh-history-substring-search ..."
git_subtrees $zsh_syntax_highlighting	"installing bundle/zsh-syntax-highlighting ..."
git_subtrees $zsh_base16		"installing bundle/zsh-base16 ..."
setup_shell 				"installing dotfile symlinks ..."
