#
# Defines environment variables.
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#
xsource "/etc/default/locale"
if [[ LC_ALL -eq '' ]]; then
    export LC_ALL="$LANG"
fi

#
# Keyboard
#
xsource "/etc/sysconfig/keyboard"

#
# Timezone
#
TZ=$(xcat /etc/timezone)

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# disable XON (^S) and XOFF (^Q) flow control keys
# http://blog.sanctum.geek.nz/terminal-annoyances/
stty -ixon


# Don't create newlines if no command is given
#accept-line () { [[ -z $BUFFER ]] && return;
#       zle .accept-line;
#};
#zle -N accept-line

[ -f /etc/DIR_COLORS ] && eval $(dircolors -b /etc/DIR_COLORS)
export ZLSCOLORS="${LS_COLORS}"
export SHELL='/bin/zsh'
export SSH_ASKPASS=/usr/bin/ksshaskpass
