#
# Executes commands at the start of an interactive session.
#

# Source init.
if [[ -s "${ZDOTDIR:-$HOME}/.X4/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.X4/init.zsh"
fi

# Customize to your needs...
