#ZSH_PROMPT="agnoster"
#ZSH_PROMPT="gentoo"
#ZSH_PROMPT="mh"
#ZSH_PROMPT="nebirhos"
#ZSH_PROMPT="skaro"       
#ZSH_PROMPT="ys"
#ZSH_PROMPT="bira"
#ZSH_PROMPT="jonathan"
#ZSH_PROMPT="miloshadzic"
#ZSH_PROMPT="norm"
#ZSH_PROMPT="vibrantink"
#ZSH_PROMPT="kafeitu"
#ZSH_PROMPT="mortalscumbag"
#ZSH_PROMPT="prose"
ZSH_PROMPT="x4"

