# Entropy / Portage
  alias e.q="equo match --multimatch --multirepo --installed"
  alias e.s="equo s"
  alias e.c="equo cleanup && equo cache clean"
  alias e.i="equo i --ask"
  alias e.rm="equo rm --ask"
  alias e.u="equo up && equo u --ask"
  alias e.up="equo up && eix-sync"
  alias e.status="while true ; do clear ; qlop -c ; sleep 2 ; done"
  alias e.log="tail -f /var/tmp/portage/*/${PKG}*/temp/build.log"
  alias e.world="equo repo mirrorsort sabayonlinux.org && equo update && equo install entropy rigo equo --relaxed && equo conf update && equo upgrade -a && equo conf update"
  alias e.sanitize="equo deptest && revdep-rebuild && prelink -amR && equo libtest && equo cleanup && equo cache clean"