#
# emacs - points to alternate init file for emacs
#

## See also:
# - http://emacswiki.org/emacs/InitFile
# - http://www.gnu.org/software/emacs/manual/html_node/emacs/General-Variables.html
# - http://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html
# - http://www.gnu.org/software/emacs/manual/html_node/elisp/Startup-Summary.html

## Before
#
# Emacs' user init file path is compiled into the program:
# - Emacs (Gnu):   ~/.emacs, _emacs, or ~/.emacs.d/init.el
# - XEmacs:        ~/.xemacs or ~/.xemacs/init.el
# - AquamacsEmacs: ~/.emacs or ~/Library/Preferences/Aquamacs\ Emacs/Preferences.el

## After
#
# If we set the $EMACSLOADPATH environmental variable, we would inadvertently
# unset the usual initial value.
#
# Instead we add a default argument that points to a script that appends our
# new load path location.
#
# Usually, you'll want to add config options to: $XDG_CONFIG_HOME/emacs/init.el

emacs_user_dir="$(dotfile emacs config dir)"

# Create the initialization file that loads all the others. (Only if it's empty.)
if [ ! -f "${emacs_user_dir}/bootstrap.el" ]; then
  printf '%s\n' \
  ';; DO NOT EDIT THIS FILE' \
  ';; This script simply adds this directory to the library search path.' \
  ';; Use the standard initialization files within this directory (e.g. init.el)' \
  "(add-to-list 'load-path \"${emacs_user_dir}\")" > ${emacs_user_dir}/bootstrap.el
fi

alias emacs="emacs -l ${emacs_user_dir}/bootstrap.el"

dotfile emacs config file init.el >/dev/null